### ISSUE TITLE
Nada sendo atualizado

### ISSUE THREAD

**Issue by samosaara** [busting-cases/Eco-C#1]
nas minhas peripécias de login google, eu não cheguei a implementar a atualização de IP nem de nada. No caso do IP preciso de um método pelo express pra conseguir o IPv4 do cliente, deve estar no res. É so mudar a linha https://github.com/busting-cases/Eco-C/blob/master/src/app.coffee#L65 pra em vez de carregar de novo da database colocar o IP atual, e claro, dar update alem do query.
Mas também não cheguei a implementar pra salvar os pontos, num event de quando tiver fechando a aba e/ou periodicamente

**Comment by JeffBusterCase** [comment]
ainda está dando erro?

**Comment by samosaara** [comment]
#2407aea
